### ISSUE TITLE
Feat: [Weapon System] 무기 시스템 구축

### ISSUE THREAD

**Issue by JK-Y41** [KIA-PROGRAMMING-38/HoloCure#14]
# 설명
(1) 무기는 동작하고(Operate) 동작이 반복되며(OperateSequence) 데미지를 줍니다(SetDamage).
(2) 무기는 획득하는 순간 초기화 하며 초기화 되면 해당 무기는 활성화 됩니다
(3) 각 VTuber 별로 고유한 무기를 가지고 게임을 시작합니다
(4) 무기는 그 자체로 게임 오브젝트가 됩니다(스프라이트 랜더러, 리짓바디, 애니메이터, 콜라이더 부착)
(5) 무기는 플레이어가 가집니다
(6) 무기는 반드시 콜라이더가 트리거입니다.
(7) 실질적인 충돌은 무기의 자식오브젝트가 담당합니다.
(8) 리짓바디는 키네틱입니다.
(9) 무기 스크립트를 제외한 컴포넌트들은 모두 비활성화합니다.

**Comment by JK-Y41** [comment]
설계 부분과 구현 부분을 나눠서 진행할 것

**Comment by ChoiSeonMun** [comment]
무기 시스템에 맞춰서 객체지향 설계 필요
